#!/bin/sh

set -e

pip3 install {{python-packages}}
sudo systemctl daemon-reload
systemctl start raspi-fan-control || echo "Can't start service"
systemctl enable raspi-fan-control || echo "Can't enable service"
